version: 2.1

dockerhub_auth: &dockerhub_auth
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

executors:
  browser:
    docker:
      - image: campgladiatortech/browser:latest
        <<: *dockerhub_auth

jobs:
  lint_and_test:
    executor: browser
    steps:
      - checkout
      - run:
          name: Ensure dependencies are present
          command: yarn install
      - run:
          name: Run linter
          command: yarn run lint
      - run:
          name: Run tests
          command: yarn run test
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
            - .cache
  deploy:
    executor: browser
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc
      - run:
          name: Publish package to NPM
          command: yarn run release
      - run:
          name: Deploy Storybook to GitHub Pages
          command: yarn run deploy

tag_regex: &tag_regex /^v[0-9]+\.[0-9]+\.[0-9]+$/

workflows:
  version: 2
  continous_integration:
    jobs:
      - lint_and_test:
          filters:
            branches:
              only: /.*/
            tags:
              only: *tag_regex

      - deploy:
          requires:
            - lint_and_test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: *tag_regex
